export const QA_CALIBRATION_RULES = [
  "Evaluate only from the supplied customer message, ticket context, requirements and agent reply.",
  "Do not invent product behaviour, causes, policies, timelines, escalations or actions.",
  "If important context is missing, state exactly what cannot be verified.",
  "Do not award full Accuracy when important claims cannot be verified.",
  "Good tone must never compensate for incorrect or unsupported information.",
  "A short reply can receive a high score when it solves the case clearly and correctly.",
  "Do not require a timeline when the issue is already fully resolved.",
  "Do not deduct Empathy merely because a simple factual question is answered directly.",
  "Empathy is expected when the customer is frustrated, worried, inconvenienced, bereaved or emotionally affected.",
  "Do not reward unnecessary apologies or excessive emotional language.",
  "Do not suggest a follow-up promise unless the agent can realistically keep it.",
  "Do not penalise missing follow-through when no further action is needed.",
  "When action is required, make clear whether the customer, agent or another team acts next.",
  "Avoid weak wording when supplied context supports a confident statement.",
  "Do not invent improvement suggestions just to fill space.",
  "The recommended reply must not introduce facts absent from supplied context.",
  "The recommended reply should sound natural and human, not like a generic AI template.",
  "Use the same language as the agent reply unless another language is requested.",
] as const;
